import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{parseCSV,analyzeRows,packetFor,ENGINE_VERSION}from'./engine';
import'./styles.css';
const money=v=>v>=1e9?`$${(v/1e9).toFixed(1)}B`:v>=1e6?`$${(v/1e6).toFixed(1)}M`:v>=1e3?`$${(v/1e3).toFixed(0)}K`:`$${Math.round(v||0)}`;
const dirEl=b=><span className={`bias ${b.toLowerCase()}`}>{b==='BULLISH'?'▲':b==='BEARISH'?'▼':'◆'} {b}</span>;
const copy={en:{upload:'Upload Barchart Options Flow CSV',simple:'Simple',advanced:'Advanced',signals:'🎯 Signals',plan:'▣ Trade Plan',risk:'⚠ Risk',refresh:'Refresh price',analyze:'Run AI opinions + synthesis',why:'Why this matters',beginner:'In plain language',coverage:'Data coverage',conf:'Confidence',score:'Smart Money Score',legacy:'Legacy benchmark'},el:{upload:'Ανέβασε Barchart Options Flow CSV',simple:'Απλό',advanced:'Προχωρημένο',signals:'🎯 Σήματα',plan:'▣ Πλάνο',risk:'⚠ Ρίσκο',refresh:'Ανανέωση τιμής',analyze:'1η + 2η γνώμη AI και σύνθεση',why:'Γιατί έχει σημασία',beginner:'Με απλά λόγια',coverage:'Κάλυψη δεδομένων',conf:'Βεβαιότητα',score:'Smart Money Score',legacy:'Legacy benchmark'}};
function App(){
 const[lang,setLang]=useState('el'),[mode,setMode]=useState('simple'),[analysis,setAnalysis]=useState(null),[selected,setSelected]=useState(null),[quote,setQuote]=useState({}),[ai,setAi]=useState({}),[tab,setTab]=useState('signals'),[status,setStatus]=useState('');const t=copy[lang];
 const current=useMemo(()=>analysis?.tickers.find(x=>x.symbol===selected)||analysis?.tickers[0],[analysis,selected]);
 async function load(e){const f=e.target.files?.[0];if(!f)return;try{setStatus('Processing…');const rows=parseCSV(await f.text());const a=analyzeRows(rows);setAnalysis(a);setSelected(a.tickers[0]?.symbol||null);setStatus(`${a.rawRows} rows · ${a.duplicates} duplicates · ${a.multiLegGroups} multi-leg groups · ${ENGINE_VERSION}`);setAi({});}catch(err){setStatus('Error: '+err.message)}e.target.value=''}
 async function refresh(){if(!current)return;setStatus('Refreshing price…');try{const r=await fetch(`/api/quote/${current.symbol}`);const d=await r.json();if(!r.ok)throw new Error(d.error);setQuote(q=>({...q,[current.symbol]:d}));setStatus('Price refreshed.')}catch(e){setStatus('Price: '+e.message)}}
 async function runAI(){if(!current)return;setAi(x=>({...x,[current.symbol]:{loading:true}}));try{const r=await fetch('/api/ai/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({packet:packetFor(current,quote[current.symbol])})});const d=await r.json();if(!r.ok)throw new Error((d.errors||[d.error]).join(' · '));setAi(x=>({...x,[current.symbol]:{...d,loading:false}}));}catch(e){setAi(x=>({...x,[current.symbol]:{loading:false,error:e.message}}));}}
 const aiNow=current?ai[current.symbol]:null;
 return <div className="app"><header><div><div className="brand">SMART FLOW <small>PRIVATE BETA</small></div><div className="sub">Options intelligence lab · Barchart upload + Twelve Data + dual AI</div></div><div className="switch"><button className={lang==='el'?'on':''}onClick={()=>setLang('el')}>ΕΛ</button><button className={lang==='en'?'on':''}onClick={()=>setLang('en')}>EN</button><button className={mode==='simple'?'on':''}onClick={()=>setMode('simple')}>{t.simple}</button><button className={mode==='advanced'?'on':''}onClick={()=>setMode('advanced')}>{t.advanced}</button></div></header>
 <section className="upload"><label>{t.upload}<input type="file" accept=".csv,text/csv" onChange={load}/></label><span>{status||'No file loaded.'}</span></section>
 {!analysis?<Empty lang={lang}/>:<main><aside><div className="asideTitle">TICKERS</div>{analysis.tickers.map(s=><button key={s.symbol}className={current?.symbol===s.symbol?'active':''}onClick={()=>{setSelected(s.symbol);setTab('signals')}}><b>{s.symbol}</b>{dirEl(s.bias)}<small>{money(s.eligiblePremium)} · C {s.confidence}%</small></button>)}</aside>
 <section className="content">{current&&<><div className="hero"><div><div className="symbol">{current.symbol} <em>{current.asset.type}</em></div>{dirEl(current.bias)} <span className="heroConf">{current.confidence}%</span>{quote[current.symbol]?.close>0&&<div className="price">${quote[current.symbol].close.toFixed(2)} <small>{quote[current.symbol].percent_change?.toFixed?.(2)}%</small></div>}</div><div className="actions"><button onClick={refresh}>{t.refresh}</button><button className="aiBtn" onClick={runAI}disabled={aiNow?.loading}>{aiNow?.loading?'AI…':t.analyze}</button></div></div>
 <div className="metrics"><Metric k={t.score}v={current.score}/><Metric k={t.conf}v={`${current.confidence}%`}/><Metric k={t.coverage}v={`${current.coverage}%`}/><Metric k="Gamma"v={current.gammaContext}/><Metric k={t.legacy}v={`${current.legacy.bias} ${current.legacy.score}`}/></div>
 <div className="tabs">{[['signals',t.signals],['plan',t.plan],['risk',t.risk]].map(([k,l])=><button className={tab===k?'active':''}onClick={()=>setTab(k)}key={k}>{l}</button>)}</div>
 {tab==='signals'&&<Signals s={current}mode={mode}lang={lang}ai={aiNow}/>} {tab==='plan'&&<TradePlan s={current}lang={lang}quote={quote[current.symbol]}/>} {tab==='risk'&&<Risk s={current}lang={lang}ai={aiNow}/>} 
 {mode==='advanced'&&<Inspector s={current}/>}</>}</section></main>}
 <footer>Educational decision-support beta · Not personalized investment advice. Signals can be wrong and options flow can represent hedging, closing activity or complex strategies.</footer></div>}
function Empty({lang}){return <div className="empty"><b>{lang==='el'?'Ξεκίνα με το ίδιο workflow που χρησιμοποιείς ήδη.':'Start with the same workflow you already use.'}</b><p>{lang==='el'?'Κατέβασε το Options Flow CSV από Barchart και ανέβασέ το εδώ. Το αρχείο αναλύεται τοπικά στον browser από το deterministic engine.':'Download the Options Flow CSV from Barchart and upload it here. The deterministic engine processes the file locally in your browser.'}</p></div>}
function Metric({k,v}){return <div className="metric"><small>{k}</small><b>{v}</b></div>}
function Signals({s,mode,lang,ai}){const gr=lang==='el';const beginner=ai?.synthesis?.beginner?.[lang];return <div className="panel"><h3>{gr?'Τι βλέπουμε':'What we see'}</h3>{mode==='simple'?<><p className="lead">{beginner||(gr?simpleGR(s):simpleEN(s))}</p><div className="explain"><b>{gr?'Γιατί έχει σημασία':'Why this matters'}</b><p>{ai?.synthesis?.why?.[lang]||(gr?whyGR(s):whyEN(s))}</p></div></>:<AdvancedSummary s={s}/>} {ai?.error&&<div className="error">AI: {ai.error}</div>}</div>}
const simpleGR=s=>s.bias==='BULLISH'?`Η δραστηριότητα στα options γέρνει προς ανοδική κατεύθυνση για ${s.symbol}. Δεν σημαίνει ότι η τιμή θα ανέβει σίγουρα· είναι ένδειξη για το πού συγκεντρώνεται η πιο ισχυρή ροή.`:s.bias==='BEARISH'?`Η δραστηριότητα στα options γέρνει προς πτωτική κατεύθυνση για ${s.symbol}. Αυτό είναι σήμα αυξημένης προσοχής, όχι βεβαιότητα ότι η τιμή θα πέσει.`:`Τα δεδομένα για ${s.symbol} είναι μικτά. Δεν υπάρχει αρκετά καθαρή κατεύθυνση ώστε να θεωρηθεί ισχυρό bullish ή bearish σήμα.`;
const simpleEN=s=>s.bias==='BULLISH'?`Options activity leans bullish for ${s.symbol}. This does not guarantee the price will rise; it shows where the stronger flow is currently concentrated.`:s.bias==='BEARISH'?`Options activity leans bearish for ${s.symbol}. This is a reason for extra caution, not a guarantee that the price will fall.`:`The data for ${s.symbol} is mixed. There is not a clean enough direction to call this a strong bullish or bearish signal.`;
const whyGR=s=>`Το score είναι ${s.score}, με βεβαιότητα ${s.confidence}% και κάλυψη ${s.coverage}%. ${s.sectorConfirmation.label==='CONFIRMED'?'Υπάρχει επιβεβαίωση από σχετικά ETF που υπάρχουν στο ίδιο upload.':s.sectorConfirmation.label==='CONFLICTING'?'Σχετικά ETF στο ίδιο upload δείχνουν αντίθετη εικόνα, οπότε μειώνεται η εμπιστοσύνη.':'Δεν υπάρχει αρκετή sector επιβεβαίωση στο συγκεκριμένο αρχείο.'}`;
const whyEN=s=>`The score is ${s.score}, with ${s.confidence}% confidence and ${s.coverage}% coverage. ${s.sectorConfirmation.label==='CONFIRMED'?'Related ETFs in the same upload confirm the direction.':s.sectorConfirmation.label==='CONFLICTING'?'Related ETFs in the same upload conflict with the signal, reducing confidence.':'There is not enough sector-confirmation data in this file.'}`;
function AdvancedSummary({s}){return <div className="grid"><Metric k="Bull weighted"v={money(s.bullishWeighted)}/><Metric k="Bear weighted"v={money(s.bearishWeighted)}/><Metric k="Opening coverage"v={`${s.openingCoverage}%`}/><Metric k="Execution coverage"v={`${s.executionCoverage}%`}/><Metric k="0DTE included"v={s.zeroDTE}/><Metric k="Multi-leg rows"v={s.multiLegTrades}/><Metric k="Sector"v={s.sectorConfirmation.label}/><Metric k="Duplicates removed"v={s.duplicates}/></div>}
function TradePlan({s,lang,quote}){const gr=lang==='el';return <div className="panel"><h3>{gr?'Πλάνο παρακολούθησης — όχι εντολή συναλλαγής':'Monitoring plan — not a trade instruction'}</h3><p>{gr?'Χρησιμοποίησε το signal σαν σενάριο που χρειάζεται επιβεβαίωση από την τιμή. Μην βασίζεις απόφαση μόνο στο options flow.':'Use the signal as a scenario that still needs confirmation from price. Do not base a decision only on options flow.'}</p><div className="steps"><div><b>1</b>{gr?'Κατεύθυνση':'Direction'}: {s.bias}</div><div><b>2</b>{gr?'Περίμενε επιβεβαίωση της τιμής και μην κυνηγάς ήδη εκτεταμένη κίνηση.':'Wait for price confirmation and avoid chasing an already extended move.'}</div><div><b>3</b>{gr?'Ακύρωσε το σενάριο αν η τιμή και το ευρύτερο sector κινούνται σταθερά αντίθετα από το signal.':'Invalidate the scenario if price and the broader sector persistently move against the signal.'}</div></div>{quote?.close?<p className="note">{gr?'Τελευταία τιμή από Twelve Data μετά από χειροκίνητο refresh:':'Latest Twelve Data price after manual refresh:'} ${quote.close.toFixed(2)}</p>:null}</div>}
function Risk({s,lang,ai}){const gr=lang==='el',risks=ai?.synthesis?.risks?.[lang];const defaults=gr?[`${100-s.coverage}% του premium δεν ταξινομείται καθαρά ως directional.`,s.multiLegTrades?`${s.multiLegTrades} γραμμές φαίνονται πιθανό μέρος multi-leg συναλλαγών.`:'Δεν εντοπίστηκαν multi-leg γραμμές με τα διαθέσιμα timestamps.',s.openingCoverage<50?'Έχουμε περιορισμένη βεβαιότητα για το αν οι θέσεις είναι opening ή closing.':'Υπάρχει σχετικά καλή κάλυψη opening/closing.']:[`${100-s.coverage}% of premium is not cleanly classified as directional.`,s.multiLegTrades?`${s.multiLegTrades} rows appear to belong to possible multi-leg trades.`:'No multi-leg rows were detected from the available timestamps.',s.openingCoverage<50?'Opening vs closing information is limited.':'Opening/closing coverage is relatively good.'];return <div className="panel"><h3>{gr?'Τι μπορεί να πάει στραβά':'What can go wrong'}</h3><ul>{(risks?.length?risks:defaults).map((x,i)=><li key={i}>{x}</li>)}</ul><div className="warning">{gr?'Options flow μπορεί να είναι hedge, closing activity ή μέρος σύνθετης στρατηγικής. Το confidence μετρά ποιότητα evidence, όχι πιθανότητα εγγυημένου κέρδους.':'Options flow can be hedging, closing activity or part of a complex strategy. Confidence measures evidence quality, not a guaranteed probability of profit.'}</div></div>}
function Inspector({s}){return <div className="panel inspector"><h3>Classification Inspector</h3><div className="table"><table><thead><tr><th>Contract</th><th>Side</th><th>Tx</th><th>Position</th><th>Direction</th><th>Premium</th><th>Conv.</th><th>Strategy</th></tr></thead><tbody>{s.trades.slice(0,80).map(t=><tr key={t.row}><td>{t.symbol} {t.expiry} {t.strike}{t.type[0]}</td><td>{t.side}</td><td>{t.tx}</td><td>{t.positionEffect}</td><td>{t.direction}</td><td>{money(t.premium)}</td><td>{Math.round(t.conviction*100)}%</td><td>{t.strategy}</td></tr>)}</tbody></table></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
