import fs from 'fs';
import {parseCSV,analyzeRows} from '../src/engine.js';
import {buildIntradayReport,reportPacket} from '../src/report.js';
const parsed=parseCSV(fs.readFileSync(new URL('../sample-etfs.csv',import.meta.url),'utf8'));
const rows=parsed.map(r=>({...r,_forcedAssetType:'ETF',_batchKind:'etfs',_batchFile:'sample-etfs.csv'}));rows._meta=parsed._meta;
const analysis=analyzeRows(rows);
const quotes=Object.fromEntries(analysis.tickers.map((s,i)=>[s.symbol,{symbol:s.symbol,close:100+i,percent_change:i%2?2.1:-1.4}]));
const report=buildIntradayReport(analysis,quotes),packet=reportPacket(report);
if(!report?.topSignal||!packet?.topSignal||!report.topBlocks.length)throw new Error('Intraday report smoke test failed');
console.log('Intraday report smoke OK:',report.topSignal.symbol,report.divergences.length,'divergences',report.topBlocks.length,'blocks');
